language: r
cache: packages
warnings_are_errors: false

before_install:
  - Rscript -e 'devtools::install_github("rstudio/keras"); library(keras); install_keras()'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
