---
title: "Automated Classification of Sleep Stages in Mice"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Automated_Classification_of_Sleep_Stages_in_Mice}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

knitr::opts_chunk$set(
  eval = all(file.exists(
    "T2T7_souris1_BL1_J2.txt",
    "T2T7_souris1_BL1_J2.edf")))

```

```{r setup}
library(rsleep)

hypnogram_t <- read_stages_compumedics(
  txt = "./T2T7_souris1_BL1_J2.txt",
  startTime = 
    edfReader::readEdfHeader(
      "./T2T7_souris1_BL1_J2.edf")$startTime)

plot_hypnogram(
  hypnogram_t[1:1000,],
  labels = c("NREM","REM","AWA"))
```

# Score


```{r}


hypnodensity <- rsleep::score_mice(
  edf = "./T2T7_souris6_BLentier.edf",#"./T2T7_souris1_BL1_J2.edf",
  model = keras::unserialize_model(readRDS("./mice_10_v2.rds")))

# hypnodensity$begin <- hypnodensity$begin+3*4
# hypnodensity$end <- hypnodensity$end+3*4
# 
hypnogram <- colnames(hypnodensity)[1:3][apply(hypnodensity,1,which.max)]
hypnogram <- data.frame("event"=hypnogram,
                        "begin" = hypnodensity$begin,
                        "end" = hypnodensity$end,
                        stringsAsFactors = FALSE)


plot_hypnogram(hypnogram[1500:2000,],
               labels = c("NREM","REM","AWA"))


psy::ckappa(data.frame(x=hypnogram$event,
                       y=hypnogram_t$event))

MLmetrics::F1_Score(hypnogram_t$event,hypnogram$event)
MLmetrics::Accuracy(hypnogram_t$event,hypnogram$event)
```


```{r}
p1 <- plot_hypnogram(
  hypnogram_t[3:1000,],
  labels = c("NREM","REM","AWA"))+
  ggplot2::ggtitle("Visual Hypnogram")

p3 <- plot_hypnodensity(
  hypnodensity, 
  stages = colnames(hypnodensity)[1:3]) +
  ggplot2::ggtitle("Algorithm Hypnodensity")

p2 <- plot_hypnogram(hypnogram,labels = c("NREM","REM","AWA")) +
  ggplot2::ggtitle("Algorithm Hypnogram")

gridExtra::grid.arrange(
  p1, p2, p3, nrow = 3)
```

# Batches

```{r}
records <- c("./JG_souris1_WE1.edf")
events <- c("./JG_souris1_WE1.txt")
```

# Write compumedics

```{r}
write_hypnogram_compumedics(hypnogram, "T2T7_souris6_BLentier.xml")
```

